name: 'Custom Node Setup'

description: 'Checks out code and sets up Node.js'
inputs:
  node-version:
    required: false
    default: '18'
    description: 'Node.js version to set up'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
