name: 'Deploy React Frontend to EC2'
description: 'Uploads React build to EC2 and restarts nginx'

secrets:
  host:
    required: true
  username:
    required: true
  key:
    required: true
inputs:
  deploy-path:
    default: /var/www/html
  temp-path:
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      run: npm install --legacy-peer-deps
      shell: bash

    - name: Build React App
      run: npm run build
      shell: bash
      
    - name: Upload build to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.username }}
        key: ${{ secrets.key }}
        source: "build"
        target: ${{ inputs.temp-path }}

    - name: Move and restart nginx
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.username }}
        key: ${{ secrets.key }}
        script: |
          sudo rm -f ${{ inputs.deploy-path }}/index.nginx-debian.html
          sudo rm -rf ${{ inputs.deploy-path }}/*
          sudo cp -r ${{ inputs.temp-path }}/build/* ${{ inputs.deploy-path }}/
          sudo chown -R www-data:www-data ${{ inputs.deploy-path }}
          sudo chmod -R 755 ${{ inputs.deploy-path }}
          sudo systemctl restart nginx
