name: 'Deploy Node.js Backend to EC2'
description: 'Deploys a Node.js backend app to EC2 via SCP and SSH'

secrets:
  host:
    required: true
  username:
    required: true
  key:
    required: true
inputs:
  app-name:
    required: true
  target-path:
    required: true

runs:
  using: "composite"
  steps:
    - name: Upload backend to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.username }}
        key: ${{ secrets.key }}
        source: "."
        target: ${{ inputs.target-path }}
        strip_components: 1

    - name: Run backend on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.username }}
        key: ${{ secrets.key }}
        script: |
          cd ${{ inputs.target-path }}
          npm install
          /usr/bin/pm2 restart ${{ inputs.app-name }} || /usr/bin/pm2 start server.js --name ${{ inputs.app-name }}
